<?php


namespace Nemundo\Content\Index\Geo\Page;


use Nemundo\Com\Template\AbstractTemplateDocument;

class GeoIndexPage extends AbstractTemplateDocument
{

    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}