<?php

namespace Nemundo\Content\Index\Log\Type;

use Nemundo\Content\Builder\ContentBuilder;
use Nemundo\Content\Index\Log\Action\LogIndexContentAction;
use Nemundo\Content\Index\Log\Data\Log\Log;
use Nemundo\Content\Type\AbstractContentBuilder;

abstract class AbstractLogContentBuilder extends AbstractContentBuilder
{



    public function buildContent()
    {


        $this->addAction(new LogIndexContentAction());


        $dataId = parent::buildContent(); // TODO: Change the autogenerated stub



        return $dataId;


    }


    protected function saveLog($contentId)
    {

        // create
        // modified


        $data = new Log();
        $data->contentId = $contentId;
        $data->message = 'bla';
        //$data->contentItemId = $this->itemContentId;
        $this->dataId = $data->save();


    }


}