<?php

namespace Nemundo\Content\Index\Tree\Com\Table;

use Nemundo\Com\TableBuilder\TableHeader;

class TreeTableHeader extends TableHeader
{
    
    public function getContent()
    {

        $this->addText('Subject');
        $this->addText('Typ');
        $this->addText('View');
        $this->addText('Item Order');
        $this->addEmpty(2);

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}