<?php

namespace Nemundo\Content\Index\Workflow\Type\Process;

use Nemundo\Content\Index\Workflow\Action\WorkflowAction;
use Nemundo\Content\Index\Workflow\Data\Workflow\Workflow;
use Nemundo\Content\Index\Workflow\Data\Workflow\WorkflowReader;
use Nemundo\Content\Type\AbstractContentBuilder;

abstract class AbstractProcessBuilder extends AbstractContentBuilder
{


    public $workflowId;


    public function buildContent()
    {
        $id =  parent::buildContent(); // TODO: Change the autogenerated stub

        $item = $this->contentType->getItem($this->getDataId());
        $this->workflowId = (new WorkflowAction())->onAction($item);

        return $id;

    }


    public function getWorkflowId() {

        //$reader = new WorkflowReader();
        //$reader->filter->andEqual($reader->model->contentId,$this->get)


        $workflowId = $this->workflowId;

        return $workflowId;


    }


    //protected function saveWorkflow() {


        /*$data = new Workflow();
        $data->contentId = $item->getContentId();
        $data->save();*/


        /*$data = new Workflow();
        $data->processId = 1;
        //$data->contentId = $this->getDataId();
        $data->save();*/

    //}


}