<?php

namespace Nemundo\Content\Translation\Type;


use Nemundo\Content\Type\AbstractSearchContentType;
use Slu3000\Type\Source\MenuSourceType;

abstract class AbstractTranslationTextContentType extends AbstractSearchContentType
{



    public function deleteType()
    {

        parent::deleteType(); // TODO: Change the autogenerated stub
        $this->deleteTranslation();

    }


    protected function deleteTranslation() {

        (new MenuSourceType())->deleteTranslation($this->dataId);



    }


}