<?php

namespace Nemundo\Content\Reader;

use Nemundo\Content\Data\ContentType\ContentTypeReader;

class ContentTypeDataReader extends ContentTypeReader
{

    public function getData()
    {
        $this->addOrder($this->model->contentType);

        return parent::getData(); // TODO: Change the autogenerated stub
    }

}