<?php

namespace Nemundo\Content\Index\Log\View;

use Nemundo\Html\Block\Div;

class AbstractContentLogView extends Div
{

    public $logDataId;

    public function getContent()
    {
        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}