<?php

namespace Nemundo\Content\Com\Navbar;


use Nemundo\Admin\Com\Navbar\AdminSiteNavbar;
use Nemundo\App\UserAction\Site\LogoutSite;
use Nemundo\App\UserAction\Site\PasswordChangeSite;
use Nemundo\Content\App\UserProfile\Site\MyUserProfileSite;
use Nemundo\Content\Index\Search\Site\Json\SearchJsonSite;
use Nemundo\Content\Index\Search\Site\SearchSite;
use Nemundo\Package\Bootstrap\Navbar\BootstrapNavbarSearchForm;

class ContentSiteNavbar extends AdminSiteNavbar
{

    public function getContent()
    {

        $this->searchMode=true;
        $this->userMode=true;

        //$this->addUserMenuSite(MyUserProfileSite::$site);
        $this->addUserMenuSite(PasswordChangeSite::$site);
        $this->addUserMenuDivider();
        $this->addUserMenuSite(LogoutSite::$site);

        $this->searchSite =  SearchSite::$site;
        $this->searchSourceSite= SearchJsonSite::$site;

        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}