<?php

namespace Nemundo\ContentTest\App\Gastro\Content\GastroWorkflow;

use Nemundo\Content\Index\Workflow\Type\Process\AbstractProcessBuilder;
use Nemundo\Content\Index\Workflow\Type\Process\AbstractProcessItem;
use Nemundo\ContentTest\App\Gastro\Data\Gastro\GastroReader;
use Nemundo\ContentTest\App\Gastro\Data\Gastro\GastroRow;

class GastroWorkflowItem extends AbstractProcessItem
{
    protected function loadItem()
    {
        $this->contentType = new GastroWorkflowType();
    }

    protected function onDataRow()
    {
        $this->dataRow = (new GastroReader())->getRowById($this->dataId);
    }

    /**
     * @return \Nemundo\Model\Row\AbstractModelDataRow|GastroRow
     */
    public function getDataRow()
    {
        return parent::getDataRow();
    }

    public function getSubject()
    {
        return $this->getDataRow()->gastro;  // parent::getSubject(); // TODO: Change the autogenerated stub
    }

}