<?php

namespace Nemundo\Content\Index\Workflow\Com\Container;

use Nemundo\Html\Block\Div;

class WorkflowContainer extends Div
{

    public function getContent()
    {



        return parent::getContent(); // TODO: Change the autogenerated stub
    }

}