<?php


namespace Nemundo\Content\Admin\Template;


use Nemundo\Admin\Com\Navigation\AdminNavigation;
use Nemundo\Com\Template\AbstractTemplateDocument;
use Nemundo\Content\Site\ContentSite;

class ContentTemplate extends AbstractTemplateDocument
{

    protected function loadContainer()
    {
        parent::loadContainer(); // TODO: Change the autogenerated stub

        $nav = new AdminNavigation($this);
        $nav->site = ContentSite::$site;


    }

}